"""The one list of key names keybot understands.

Every part of the project reads its key names from here: the dev server,
the webapp's key picker, and the board itself, which checks this list
against the real adafruit_hid Keycode library when it boots. The names
used to be typed out by hand in three places, they drifted, and recorded
arrow keys and digits failed on the hardware as a result.

Each entry is (NAME, label): NAME is what the firmware sends to
adafruit_hid, label is what a person calls that key. The webapp shows
both, so "8 (EIGHT)" is what you pick and "EIGHT" is what gets stored.

This file runs on CircuitPython, so it is plain data with no imports.
"""

KEYCODES = [
    ("A", "A"),
    ("B", "B"),
    ("C", "C"),
    ("D", "D"),
    ("E", "E"),
    ("F", "F"),
    ("G", "G"),
    ("H", "H"),
    ("I", "I"),
    ("J", "J"),
    ("K", "K"),
    ("L", "L"),
    ("M", "M"),
    ("N", "N"),
    ("O", "O"),
    ("P", "P"),
    ("Q", "Q"),
    ("R", "R"),
    ("S", "S"),
    ("T", "T"),
    ("U", "U"),
    ("V", "V"),
    ("W", "W"),
    ("X", "X"),
    ("Y", "Y"),
    ("Z", "Z"),
    ("ZERO", "0"),
    ("ONE", "1"),
    ("TWO", "2"),
    ("THREE", "3"),
    ("FOUR", "4"),
    ("FIVE", "5"),
    ("SIX", "6"),
    ("SEVEN", "7"),
    ("EIGHT", "8"),
    ("NINE", "9"),
    ("ENTER", "Enter"),
    ("RETURN", "Return"),
    ("ESCAPE", "Escape"),
    ("BACKSPACE", "Backspace"),
    ("TAB", "Tab"),
    ("SPACE", "Space"),
    ("SPACEBAR", "Spacebar"),
    ("DELETE", "Delete"),
    ("MINUS", "-"),
    ("EQUALS", "="),
    ("LEFT_BRACKET", "["),
    ("RIGHT_BRACKET", "]"),
    ("BACKSLASH", "\\"),
    ("POUND", "#"),
    ("SEMICOLON", ";"),
    ("QUOTE", "'"),
    ("GRAVE_ACCENT", "`"),
    ("COMMA", ","),
    ("PERIOD", "."),
    ("FORWARD_SLASH", "/"),
    ("CAPS_LOCK", "Caps lock"),
    ("F1", "F1"),
    ("F2", "F2"),
    ("F3", "F3"),
    ("F4", "F4"),
    ("F5", "F5"),
    ("F6", "F6"),
    ("F7", "F7"),
    ("F8", "F8"),
    ("F9", "F9"),
    ("F10", "F10"),
    ("F11", "F11"),
    ("F12", "F12"),
    ("F13", "F13"),
    ("F14", "F14"),
    ("F15", "F15"),
    ("F16", "F16"),
    ("F17", "F17"),
    ("F18", "F18"),
    ("F19", "F19"),
    ("F20", "F20"),
    ("F21", "F21"),
    ("F22", "F22"),
    ("F23", "F23"),
    ("F24", "F24"),
    ("PRINT_SCREEN", "Print screen"),
    ("SCROLL_LOCK", "Scroll lock"),
    ("PAUSE", "Pause"),
    ("INSERT", "Insert"),
    ("HOME", "Home"),
    ("PAGE_UP", "Page up"),
    ("END", "End"),
    ("PAGE_DOWN", "Page down"),
    ("RIGHT_ARROW", "Right arrow"),
    ("LEFT_ARROW", "Left arrow"),
    ("DOWN_ARROW", "Down arrow"),
    ("UP_ARROW", "Up arrow"),
    ("KEYPAD_NUMLOCK", "Keypad num lock"),
    ("KEYPAD_FORWARD_SLASH", "Keypad /"),
    ("KEYPAD_ASTERISK", "Keypad *"),
    ("KEYPAD_MINUS", "Keypad -"),
    ("KEYPAD_PLUS", "Keypad +"),
    ("KEYPAD_ENTER", "Keypad enter"),
    ("KEYPAD_ZERO", "Keypad 0"),
    ("KEYPAD_ONE", "Keypad 1"),
    ("KEYPAD_TWO", "Keypad 2"),
    ("KEYPAD_THREE", "Keypad 3"),
    ("KEYPAD_FOUR", "Keypad 4"),
    ("KEYPAD_FIVE", "Keypad 5"),
    ("KEYPAD_SIX", "Keypad 6"),
    ("KEYPAD_SEVEN", "Keypad 7"),
    ("KEYPAD_EIGHT", "Keypad 8"),
    ("KEYPAD_NINE", "Keypad 9"),
    ("KEYPAD_PERIOD", "Keypad ."),
    ("KEYPAD_BACKSLASH", "Keypad \\"),
    ("KEYPAD_EQUALS", "Keypad ="),
    ("APPLICATION", "Application menu"),
    ("POWER", "Power"),
    ("LEFT_CONTROL", "Left control"),
    ("CONTROL", "Control"),
    ("LEFT_SHIFT", "Left shift"),
    ("SHIFT", "Shift"),
    ("LEFT_ALT", "Left alt"),
    ("ALT", "Alt"),
    ("OPTION", "Option"),
    ("LEFT_GUI", "Left command"),
    ("GUI", "Command or Windows"),
    ("WINDOWS", "Windows"),
    ("COMMAND", "Command"),
    ("RIGHT_CONTROL", "Right control"),
    ("RIGHT_SHIFT", "Right shift"),
    ("RIGHT_ALT", "Right alt"),
    ("RIGHT_GUI", "Right command"),
]
